name: Update Submodule HOME
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-home:
    runs-on: ubuntu-latest
    steps:
      # Use PAT instead of default GITHUB_TOKEN to trigger docker-build workflow on push.
      # GitHub Actions doesn't trigger workflows when using the default GITHUB_TOKEN.
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: false
          fetch-depth: 1
      - name: Update HOME from Upstream
        run: |
          git submodule update --init --remote --depth=1 -- HOME
      - name: Commit & Push if Changed
        run: |
          if git diff --quiet -- HOME; then
            echo 'HOME is already up to date'
            exit
          fi
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add HOME
          git commit -m '; chore: update submodule HOME'
          git push origin 'HEAD:${{ github.ref_name }}'
