name: Update Submodule make-gcc/src
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1
      - name: Update GCC from Upstream
        run: |
          git submodule update --init --remote --depth=1 -- make-gcc/src
      # Use PAT instead of default GITHUB_TOKEN to trigger docker-build workflow on push.
      # GitHub Actions doesn't trigger workflows when using the default GITHUB_TOKEN.
      # Required PAT permissions: contents: write
      - name: Commit & Push if Changed
        run: |
          if git diff --quiet -- make-gcc/src; then
            echo 'GCC (make-gcc/src) is already up to date'
            exit
          fi
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add make-gcc/src
          git commit -m '; chore: update submodule make-gcc/src'
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} 'HEAD:${{ github.ref_name }}'
